#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# GAMMATRONIC-MIB::psUnit
# .1.3.6.1.4.1.6050.1.1.1.0 = STRING: "OR ADIR"
# .1.3.6.1.4.1.6050.1.1.2.0 = STRING: "Gamatronic"
# .1.3.6.1.4.1.6050.1.1.3.0 = STRING: "YUASA"
# .1.3.6.1.4.1.6050.1.1.4.0 = STRING: "50-6"
# .1.3.6.1.4.1.6050.1.1.5.0 = STRING: "SC1006"
# .1.3.6.1.4.1.6050.1.1.6.0 = STRING: "abc"
# .1.3.6.1.4.1.6050.1.1.7.0 = STRING: "SNMP"
# .1.3.6.1.4.1.6050.1.1.8.0 = STRING: "83-06-06-15"


def inventory_gamatronic_ups(info):
    if len(info) > 0:
            yield None, {}

def check_gamatronic_ups(item, params, info):
    sys_name, manufacture, bat_type, ps_type, controller_type, sw_ver, \
        proto_ver, serial = info[0]

    infotext = "Type: %s (%s), Serial: %s, Batt: %s, Power Supply: %s" % \
               (controller_type, sys_name, serial, bat_type, ps_type)
    return 0, infotext


check_info["gamatronic_ups"] = {
    "inventory_function"        : inventory_gamatronic_ups,
    "check_function"            : check_gamatronic_ups,
    "service_description"       : 'Chassis Info',
    "snmp_info"                 : (".1.3.6.1.4.1.6050.1.1", [ #  GAMMATRONIC-MIB::psUnit
                                          "1.0",    # psUnitSysName
                                          "2.0",    # psUnitManufacture
                                          "3.0",    # psUnitBatteryType
                                          "4.0",    # psUnitPSType
                                          "5.0",    # psUnitControllerType
                                          "6.0",    # psUnitSoftwareVersion
                                          "7.0",    # psUnitComProtocolVersion
                                          "8.0",    # psUnitSerialNumber
                                  ]),
    "snmp_scan_function"        : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.6050",

}

# Fin.

