#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# +------------------------------------------------------------------------------+
# | Software Information Slot #01                                                |
# +------------------------------------------------------------------------------+
# | Installed Package   : leos-04-08-00-0096                                     |
# | Running Package     : leos-04-08-00-0096                                     |
# | Running Kernel      : Build 4529 10:16:02 Sep  2 2009 C:\AR\BUILD_4529\      |
# | Running Application : Build 8129 04:10:09 Jan 19 2012 C:\p4\leos\0480\       |
# | Running MIB version : 02-08-00-0015                                          |
# | Release Status      : GA                                                     |
# +------------------------------------------------------------------------------+
# SNMPv2-SMI::enterprises.6141.2.60.10.1.1.3.1.1.1 = STRING: "saos-06-13-00-0318"
# SNMPv2-SMI::enterprises.6141.2.60.10.1.1.3.1.2.1 = STRING: "saos-06-13-00-0318"
# SNMPv2-SMI::enterprises.6141.2.60.10.1.1.3.1.3.1 = ""
# SNMPv2-SMI::enterprises.6141.2.60.10.1.1.3.1.4.1 = STRING: "GA"

# NOTE: When we get access to a Ciena chassis with multiple blades we will need to cater
# for that.

ciena_software_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.6141.1")

def inventory_ciena_software_info(info):
    for blade_idx, installed_pkg, running_pkg, release_status in info:
        if installed_pkg != "":
            yield None, {}

def check_ciena_software_info(item, no_params, info):
    for blade_idx, installed_pkg, running_pkg, release_status in info:
        infotext = 'Installed: %s, Running: %s, Release: %s' % \
                   ( installed_pkg, running_pkg, release_status)
        return 0, infotext


check_info["ciena_software"] = {
    "inventory_function"        : inventory_ciena_software_info,
    "check_function"            : check_ciena_software_info,
    "service_description"       : 'Chassis Software',
    "snmp_info"                 : (".1.3.6.1.4.1.6141.2.60.10.1.1.3.1", [ # WWP-LEOS-SW-XGRADE-MIB::wwpLeosBladePackageInfoTable
                                      OID_END,    # blade index
                                          "1",    # wwpLeosBladeInstPackageVer
                                          "2",    # wwpLeosBladeRunPackageVer
                                          "4",    # wwpLeosBladeInstPackageRlsStatus
                                  ]),
    "snmp_scan_function"        : ciena_software_scan,

}

# Fin.

