#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# +---------------- CHASSIS DEVICE ID ----------------+
# | Parameter                 |                       |
# +---------------------------+-----------------------+
# | Device Type               | 086                   |
# | Part Number/Revision      | 1703960840/006        |
# | Serial Number             | M6713730              |
# | Manufactured Date         | 20120627              |
# | Chassis MAC Address       | 00:23:8a:11:7c:50     |
# | Param Version             | 005                   |
# +---------------------------+-----------------------+
#
# .1.3.6.1.4.1.6141.2.60.11.1.1.1.50.0 = Hex-STRING: 00 23 8A 11 7C 50 
# .1.3.6.1.4.1.6141.2.60.11.1.1.1.51.0 = STRING: "086"
# .1.3.6.1.4.1.6141.2.60.11.1.1.1.52.0 = STRING: "M6713730"
# .1.3.6.1.4.1.6141.2.60.11.1.1.1.53.0 = Hex-STRING: 07 DC 1B 06 00 00 00 00 2B 00 00 
# .1.3.6.1.4.1.6141.2.60.11.1.1.1.54.0 = STRING: "005"


def inventory_ciena_chassis_info(info):
    for mac, dev_id, serial_no, mfg_date, version in info:
        if mac != "":
            yield None, {}

def check_ciena_chassis_info(item, params, info):
    for mac, dev_id, serial_no, mfg_date, version in info:
        infotext = 'MAC: %s, Type: %s, Serial: %s' % \
                   ( ciena_render_mac_address(mac), dev_id, serial_no )
        return 0, infotext


check_info["ciena_chassis"] = {
    "inventory_function"        : inventory_ciena_chassis_info,
    "check_function"            : check_ciena_chassis_info,
    "service_description"       : 'Chassis Info',
    "snmp_info"                 : (".1.3.6.1.4.1.6141.2.60.11.1.1.1", [ # WWP-LEOS-CHASSIS-MIB::wwpLeosChassisModule
                                BINARY("50.0"),   #  wwpLeosChassisMacAddress                 0
                                       "51.0",    #  wwpLeosChassisDeviceId                   1
                                       "52.0",    #  wwpLeosChassisSerialNumber               2
                                BINARY("53.0"),   #  wwpLeosChassisMfgDate                    3
                                       "54.0",    #  wwpLeosChassisParamVersion               4
                                  ]),
    "snmp_scan_function"        : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.6141.1"),

}

# Fin.

