#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.6141.2.60.12.1.11.9.0 = INTEGER: 13


ciena_system_cpu_util_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.6141.1")

ciena_system_cpu_util_info = (".1.3.6.1.4.1.6141.2.60.12.1.11", [ # WWP-LEOS-SYSTEM-CONFIG-MIB::wwpLeosSystemCpuUtilization
                                        "9.0",   # wwpLeosSystemCpuUtilizationLast60Seconds
                             ])

ciena_system_cpu_util_default_levels = (50.0, 80.0)

def inventory_ciena_system_cpu_util(info):
    if info and info[0][0].isdigit():
        return [ (None, "ciena_system_cpu_util_default_levels")]

def check_ciena_system_cpu_util(item, params, info):
    raw_cpu = info[0][0]
    if not raw_cpu.isdigit():
        return 3, 'No information about the CPU utilization available'

    cpu_util = float(raw_cpu)
    state = 0
    infotext = "%.1f%% utilization in the last 60 seconds" % cpu_util

    warn, crit = params
    if cpu_util >= crit:
        state = 2
    elif cpu_util >= warn:
        state = 1
    if state > 0:
        infotext += " (warn/crit at %.1f%%/%.1f%%)" % (warn, crit)

    return state, infotext, [("util", cpu_util, warn, crit, 0, 100)]

check_info["ciena_system_cpu_util"] = {
    "inventory_function"      : inventory_ciena_system_cpu_util,
    "check_function"          : check_ciena_system_cpu_util,
    "service_description"     : "CPU utilization",
    "has_perfdata"            : True,
    "snmp_info"               : ciena_system_cpu_util_info,
    "snmp_scan_function"      : ciena_system_cpu_util_scan,
    "group"                   : "cpu_utilization",
}

