#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.4458.1000.1.1.44.0 = INTEGER: 31

radwin_5000_temp_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.4458.20.5.1")

radwin_5000_temp_info = (".1.3.6.1.4.1.4458.1000.1.1", ["44.0"])

factory_settings["radwin_5000_temp_default_levels"] = {
    "levels" : (50, 60),
}

def inventory_radwin_5000_temp(info):
    if info[0][0].isdigit():
        return [ ("Chassis", {}) ]

def check_radwin_5000_temp(item, params, info):
    temp = float(info[0][0])
    return check_temperature(temp, params, "radwin_5000_%s" % item)

check_info["radwin_5000_temp"] = {
    "inventory_function"        : inventory_radwin_5000_temp,
    "check_function"            : check_radwin_5000_temp,
    "service_description"       : 'Temperature %s',
    'has_perfdata'              : True,
    "snmp_info"                 : radwin_5000_temp_info,
    "snmp_scan_function"        : radwin_5000_temp_scan,
    'group'                     : 'temperature',
    'default_levels_variable'   : 'radwin_5000_temp_default_levels',
    'includes'                  : [ "temperature.include" ],
}

# Fin.

