#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# SNMPv2-SMI::enterprises.14988.1.1.17.1.1.2.1 = STRING: "part0"
# SNMPv2-SMI::enterprises.14988.1.1.17.1.1.3.1 = INTEGER: 128
# SNMPv2-SMI::enterprises.14988.1.1.17.1.1.4.1 = STRING: "RouterOS v6.37.1 Sep/30/2016 10:28:41"
# SNMPv2-SMI::enterprises.14988.1.1.17.1.1.5.1 = INTEGER: 1
# SNMPv2-SMI::enterprises.14988.1.1.17.1.1.6.1 = INTEGER: 1

mikrotik_partition_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.14988.1")

mikrotik_partition_info = (".1.3.6.1.4.1.14988.1.1.17.1.1", [   # MIKROTIK.MIB:: mtxrPartition
                                OID_END,    # index
                                    "2",    # mtxrPartitionName
                                    "3",    # mtxrPartitionSize
                                    "4",    # mtxrPartitionVersion
                                    "5",    # mtxrPartitionActive
                                    "6",    # mtxrPartitionRunning
                         ])


def inventory_mikrotik_partition(info):
    for idx, name, size, version, active, running in info:
        if running == "1":
            yield idx, {}

def check_mikrotik_partition(item, params, info):
    for idx, name, size, version, active, running in info:
        yield 0, "%s, %sMB, %s" % (name, size, version)


check_info["mikrotik_partition"] = {
    "inventory_function"        : inventory_mikrotik_partition,
    "check_function"            : check_mikrotik_partition,
    "service_description"       : 'Partition %s',
    "snmp_info"                 : mikrotik_partition_info,
    "snmp_scan_function"        : mikrotik_partition_scan,
}

# Fin.

