#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# SNMPv2-SMI::enterprises.14988.1.1.7.3.0 = STRING: "82230825B608"
# SNMPv2-SMI::enterprises.14988.1.1.7.4.0 = STRING: "6.42.3"
# SNMPv2-SMI::enterprises.14988.1.1.7.6.0 = STRING: "May/24/2018 09:20:22"
# SNMPv2-SMI::enterprises.14988.1.1.7.7.0 = STRING: "6.42.3"

mikrotik_health_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.14988.1")

mikrotik_health_info = (".1.3.6.1.4.1.14988.1.1.7", [ #  MIKROTIK.MIB::mtxrSystem
                                "3.0", # MIKROTIK.MIB::mtxrSerialNumber
                                "4.0", # MIKROTIK.MIB::mtxrFirmwareVersion
                                "6.0", # MIKROTIK.MIB::mtxrBuildTime
                                "7.0", # MIKROTIK.MIB::mtxrFirmwareUpgradeVersion
                       ])

def inventory_mikrotik_system(info):
    yield None, {}

def check_mikrotik_system(no_item, no_params, info):
    serial, sw_ver, build_time, sw_upgrade_ver = info[0]
    infotext = "Serial: %s, Firmware: %s, %s" % (serial, sw_ver, build_time)
    return 0, infotext

check_info["mikrotik_system"] = {
    "inventory_function"        : inventory_mikrotik_system,
    "check_function"            : check_mikrotik_system,
    "service_description"       : 'Chassis Info',
    "snmp_info"                 : mikrotik_health_info,
    "snmp_scan_function"        : mikrotik_health_scan,
}

# Fin.

