#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.9.9.150.1.1.1.0 = Gauge32: 147

mikrotik_aaa_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.14988.1") and \
                                oid(".1.3.6.1.4.1.9.9.150.1.1.1.0") != None

mikrotik_aaa_info = (".1.3.6.1.4.1.9.9.150.1.1", ["1.0"])  #  CISCO-AAA-SESSION-MIB::casnActiveTableEntries

def inventory_mikrotik_aaa(info):
    if info[0][0].isdigit() and int(info[0][0]) > 0:
        return [ (None, None) ]

def check_mikrotik_aaa(item, params, info):
    sessions = int(info[0][0])
    infotext = "Active sessions: %d" % sessions
    perfdata = [("ppp_sessions", "%d" % sessions)]
    return (0, infotext, perfdata)

check_info["mikrotik_aaa"] = {
    "inventory_function"        : inventory_mikrotik_aaa,
    "check_function"            : check_mikrotik_aaa,
    "service_description"       : 'PPP Sessions',
    'has_perfdata'              : True,
    "snmp_info"                 : mikrotik_aaa_info,
    "snmp_scan_function"        : mikrotik_aaa_scan,
}

# Fin.


