#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#

# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.1 = STRING: "Total Rectifier Current"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.2 = STRING: "Avg DC Voltage"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.3 = STRING: "Avg AC Voltage"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.4 = STRING: "# Acquired Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.5 = STRING: "# Sourcing Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.6 = STRING: "# Failed Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.7 = STRING: "# Minor Alarm Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.8 = STRING: "# Comms Lost Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.9 = STRING: "# AC Failed Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.10 = STRING: "# Out Of Tolerance"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.11 = STRING: "# Locked Out Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.12 = STRING: "# Equalize Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.13 = STRING: "# Current Limit Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.14 = STRING: "# Power Limit Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.15 = STRING: "# Fan Failed Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.16 = STRING: "# Power Saving Rectifiers"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.17 = STRING: "Avg. AC Phase R"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.18 = STRING: "Avg. AC Phase S"
# .1.3.6.1.4.1.7309.4.1.6.3.2.1.4.19 = STRING: "Avg. AC Phase T"


def inventory_cordex_rectifier(info):
    for line in info:
        if "Acquired Rectifiers" in line[2]:
          yield None, {}

def check_cordex_rectifier(item, params, info):
    rectifier_cnt = 0
    rectifier_fail = 0
    rectifier_alarm = 0
    for line in info:
        if "# Acquired" in line[2]:
            rectifier_cnt = int(line[1])
        elif "# Failed" in line[2]:
            rectifier_fail = int(line[1])
        elif "# Minor Alarm" in line[2]:
            rectifier_alarm = int(line[1])

    yield 0, "Acquired: %d" % rectifier_cnt

    if rectifier_fail > 0:
        state = 2
    else:
        state = 0
    yield state, ("Failures: %d" % rectifier_fail)

    if rectifier_alarm > 0:
        state = 2
    else:
        state = 0
    yield state, ("Alarms: %d" % rectifier_alarm)

check_info["cordex_rectifier"] = {
    "check_function"        : check_cordex_rectifier,
    "inventory_function"    : inventory_cordex_rectifier,
    "service_description"   : "Rectifier",
    "snmp_info"             : ( ".1.3.6.1.4.1.7309.4.1.6.3.2", [  # AlphaPowerSystem-MIB::dcPwrSysRectIpTable
                                       "1.2",  # dcPwrSysRectIpName
                                       "1.3",  # dcPwrSysRectIpIntegerValue
                                       "1.4",  # dcPwrSysRectIpStringValue
                              ]),
    "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.7309.4",
}

# Fin.

