#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.7309.4.1.2.1.0 = STRING: "Bryanston JW"
# .1.3.6.1.4.1.7309.4.1.2.8.0 = STRING: "CXC"
# .1.3.6.1.4.1.7309.4.1.2.9.0 = STRING: "900000125"
# .1.3.6.1.4.1.7309.4.1.2.10.0 = STRING: "030-851-20-040"
# .1.3.6.1.4.1.7309.4.1.2.11.0 = STRING: "2.27"
# .1.3.6.1.4.1.7309.4.1.2.12.0 = STRING: "2015/09/25 11:38:26"


def inventory_cordex(info):
    for site_name, sys_type, sys_serial, sys_number, sw_ver, sw_date in info:
        if len(sys_type) > 0:
            yield sys_type, {}

def check_cordex(item, _no_params, info):
    for site_name, sys_type, sys_serial, sys_number, sw_ver, sw_date in info:
        if item == sys_type:
            infotext = "%s, System: %s, Serial: %s, SW: %s, %s" % \
                       ( site_name, sys_number, sys_serial, sw_ver, sw_date)

            return (0, infotext)

check_info['cordex'] = {
  "inventory_function"  : inventory_cordex,
  "check_function"      : check_cordex,
  "service_description" : "%s Info",
  "snmp_info"           : (".1.3.6.1.4.1.7309.4.1.2" , [
                                  '1.0',  # dcPwrSysSiteName           0
                                  '8.0',  # dcPwrSysSystemType         1
                                  '9.0',  # dcPwrSysSystemSerial       2
                                 '10.0',  # dcPwrSysSystemNumber       3
                                 '11.0',  # dcPwrSysSoftwareVersion    4
                                 '12.0',  # dcPwrSysSoftwareTimestamp  5
                          ]),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.7309.4",
}

# Fin.

