#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.1 = STRING: "Rectifier Fail"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.2 = STRING: "Rectifier Minor"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.3 = STRING: "Rect. Major Fail Count"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.4 = STRING: "Rect. Minor Fail Count"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.5 = STRING: "Rectifier Lockout"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.6 = STRING: "Out Of Tolerance"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.7 = STRING: "Rect. Comms Lost"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.8 = STRING: "Rect. Equalize Activated"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.9 = STRING: "Rect. AC Mains Fail"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.10 = STRING: "Max Rectifiers Exceeded"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.11 = STRING: "Fan Fail Alarm"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.12 = STRING: "Power Save"
# .1.3.6.1.4.1.7309.4.1.5.1.2.1.4.13 = STRING: "Urgent Rect. AC Mains Fail"

def inventory_cordex_alarm(info):
    for line in info:
        if "Rectifier Fail" in line[2]:
          yield None, {}

def check_cordex_alarm(item, params, info):
    alarm_cnt = 0
    alarmtext = ""
    for line in info:
        if int(line[1]) > 0:
            alarmtext += ", %s" % line[2]
            alarm_cnt += 1

    if alarm_cnt > 0:
        state = 2
        infotext = "Count: %d" % alarm_cnt  + alarmtext
    else:
        state = 0
        infotext = "None"

    return (state, infotext)

check_info["cordex_alarm"] = {
    "check_function"        : check_cordex_alarm,
    "inventory_function"    : inventory_cordex_alarm,
    "service_description"   : "Alarm",
    "snmp_info"             : ( ".1.3.6.1.4.1.7309.4.1.5.1.2", [  # AlphaPowerSystem-MIB::dcPwrSysRectAlrmTable
                                       "1.2",  # dcPwrSysRectAlrmName
                                       "1.3",  # dcPwrSysRectAlrmIntegerValue
                                       "1.4",  # dcPwrSysRectAlrmStringValue
                              ]),
    "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.7309.4",
}

# Fin.

