#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# The Huawei RTN905 radios return a empty string for the system description OID.
# We check sysContact for Huawei identifier.
#
# SNMPv2-MIB::sysDescr.0 = STRING: 
# SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.2011.2.25.1
# SNMPv2-MIB::sysContact.0 = STRING: Huawei Technologies Ltd. Co.
# SNMPv2-MIB::sysName.0 = STRING: Optix product
# SNMPv2-MIB::sysLocation.0 = STRING: Shenzhen city, PR China

def inventory_huawei(info):
    if len(info[0]) >= 3:
        return [ (None, None) ]

def check_huawei(checktype, params, info):
    if len(info[0]) >= 3:
        return (0, ', '.join([ info[0][i] for i in [1, 2, 0] if info[0][i] ]))
    else:
        return (3, "No data retrieved")

check_info["huawei"] = {
    'check_function':          check_huawei,
    'inventory_function':      inventory_huawei,
    'service_description':     'SNMP Info',
    'snmp_info':               ('.1.3.6.1.2.1.1', ['4.0', '5.0', '6.0']),
    'snmp_scan_function':      lambda oid: oid(".1.3.6.1.2.1.1.4.0") == "Huawei Technologies Ltd. Co.",
}

# Fin.
