#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#

mgeups_scan = lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.705.1.2"

mgeups_info = (".1.3.6.1.4.1.705.1.1", [   # MG-SNMP-UPS-MIB::upsmgIdent
                            "1.0",    # upsmgIdentFamilyName
                            "2.0",    # upsmgIdentModelName
                            "4.0",    # upsmgIdentFirmwareVersion
                            "7.0",    # upsmgIdentSerialNumber
                          ])

def inventory_mgeups(info):
    if len(info[0]) > 0:
        yield "Info", {}

def check_mgeups(item, params, info):
    state = 0
    infotext = ""

    if item == "Info":
        name, model, fw_ver, serial = info[0]
        infotext = "Type: %s, Model: %s, FW: %s, Serial %s" % (name, model, fw_ver, serial)
  
    return (state, infotext)

check_info["mgeups"] = {
    "inventory_function"        : inventory_mgeups,
    "check_function"            : check_mgeups,
    "service_description"       : 'Device %s',
    "snmp_info"                 : mgeups_info,
    "snmp_scan_function"        : mgeups_scan,
}

# Fin.

