#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# this file is part of mkp package "mikrotik"
# see package description and ~/local/share/doc/check_mk/mikrotik
# for details and maintainer
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Router/Switch:
#<<<mikrotik_api_board>>>
#factory-firmware 3.41
#firmware-type tilegx
#routerboard True
#serial-number XXXXXX
#upgrade-firmware 6.43.2
#model CCR1036-12G-4S
#current-firmware 3.41
#routeros-tile 6.43.2
#
# AP:
#<<<mikrotik_api_board>>>
#factory-firmware 6.42.7
#firmware-type ipq4000L
#upgrade-firmware 6.44.3
#routerboard True
#serial-number XXXXXX
#board-name cAP ac
#model RouterBOARD cAP Gi-5acD2nD
#current-firmware 6.44.3
#routeros-arm 6.44.3
#
# cloud hosted:
#<<<mikrotik_api_board>>>
#routerboard False
#routeros-x86 6.43.2
#


#
# parse function
#
def parse_mikrotik_api_board(info):
    data = {}
    for line in info:

        #
        # Cloud hosted do not tell model
        #
        if 'routerboard false' in ' '.join(line):
            line = ['model', 'Cloud hosted']

        for what in ['serial-number', 'routeros', 'model', 'firmware']:

            if what in line[0]:
                data[line[0]] = ' '.join(line[1:])                     

    return data


#
# inventory function
#
def inventory_mikrotik_api_board(parsed):
    if parsed:
        yield None, {}

#
# check function
#
def check_mikrotik_api_board(item, params, parsed):

    infotext  = '%s: %s' % ('model',  parsed['model'])

    #
    # this info is always returned
    #
    for what in ['routeros', 'serial-number']:
        for i in parsed.keys():
            if what in i:
               infotext += ', %s: %s' % (i, parsed[i])

    #
    # firmware info might be missing
    #
    if 'firmware' in ' '.join(parsed):
        multiline ='\n'
        for i in parsed.keys():
                if 'firmware' in i:
                    multiline += '%s: %s, ' % (i, parsed[i])
        infotext += multiline

    #
    # This is the end
    #
    return 0, infotext

#
# check info
#
check_info['mikrotik_api_board'] = {
    'parse_function'            : parse_mikrotik_api_board,
    'inventory_function'        : inventory_mikrotik_api_board,
    'check_function'            : check_mikrotik_api_board,
    'service_description'       : 'RouterOS Info',
    'has_perfdata'              : True,
}

