#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2018             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Techfu / Greg Wildman <greg.wildman@techfu.co.za> - 2018

# Example Output
#
# .1.3.6.1.4.1.1807.30.1.1.1.4.3 = INTEGER: 275


# Should pickup 1807.1.2.250, 1807.1.2.251, 1807.1.2.259 and 1807.1.2.274
intracom_temp_scan = lambda oid: ".1.3.6.1.4.1.1807.1.2.2" in oid(".1.3.6.1.2.1.1.2.0")

intracom_temp_info = ( ".1.3.6.1.4.1.1807.30.1.1.1", [ "4" ] )


factory_settings["intracom_temp_default_levels"] = {
    "levels" : (45, 50),
}

def inventory_intracom_temp(info):
    yield "Chassis", {}

def check_intracom_temp(item, params, info):
    temp = float(info[0][0]) / 10.0
    return check_temperature(temp, params, "intracom_%s" % item)


check_info["intracom_temp"] = {
    "inventory_function"        : inventory_intracom_temp,
    "check_function"            : check_intracom_temp,
    "service_description"       : "Temperature %s",
    "has_perfdata"              : True,
    "snmp_info"                 : intracom_temp_info,
    "snmp_scan_function"        : intracom_temp_scan,
    "group"                     : "temperature",
    "default_levels_variable"   : "intracom_temp_default_levels",
    "includes"                  : [ "temperature.include" ],
}

# Fin.

